Repository Z-Devs-platzi/event_up-front, pull requests merged in 2020-09, with the labels that each got.

#71 Feature/event provider
  src/components/AppWrapper/index.js
  src/components/SponsorItem/index.js
  src/components/SponsorsForm/index.js
  src/containers/EventForms/index.js
  src/context/auth-context.js
  src/context/event-context.js
  src/routes/AppRoutes.js
Labels: API, enhancement

#72 Add enpoints base enpoints
  src/utility/enpoints/event.js
  src/utility/enpoints/event.test.js
  src/utility/enpoints/expositor.js
  src/utility/enpoints/expositor.test.js
  src/utility/enpoints/sponsors.js
Labels: API, enhancement

#73 Feature/add templates speakers
  src/components/templates/SpeakerCard/SpeakerCard.stories.js
  src/components/templates/SpeakerCard/index.js
  src/components/templates/SpeakerCard/styles.js
  src/components/templates/TemplateSpeakers/TemplateSpeakers.stories.js
  src/components/templates/TemplateSpeakers/index.js
  src/components/templates/TemplateSpeakers/styles.js
Labels: UI/UX

#74 Feature/list events and Genenral form
  src/components/CalendarDatePicker/CalendarDatePicker.test.js
  src/components/CalendarDatePicker/index.js
  src/components/EventRow/index.js
  src/components/EventsList/index.js
  src/components/GeneralForm/index.js
  src/components/SponsorsForm/index.js
  src/components/TextArea/index.js
  src/containers/EventForms/index.js
  src/containers/Events/index.js
  src/context/event-context.js
  src/routes/AppRoutes.js
  src/utility/api/index.js
  src/utility/enpoints/event.js
Labels: API, enhancement, hooks, hotfix
