Repository Z-Devs-platzi/event_up-front, pull requests merged in 2020-08, with the labels that each got.

#1 CI & Stories
  .github/workflows/cd.yml
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Button/Button.stories.js
  src/index.js
  src/routes/App.js
  src/utility/strings/index.js
  src/utility/strings/strings.test.js
Labels: dependencies, testing

#9 Feature/auth routes
  src/auth-provider.js
  src/auth-provider.test.js
  src/containers/Home/index.js
  src/context/app-provider.js
  src/context/auth-context.js
  src/context/user-context.js
  src/routes/App.js
  src/routes/AppRoutes.js
  src/routes/LandingRoutes.js
  src/routes/PrivateRoute.js
  src/routes/Routes.js
  src/utility/api/api.test.js
  src/utility/api/index.js
  src/utility/enpoints/auth.js
  src/utility/enpoints/auth.test.js
  src/utility/enpoints/search.js
  storybook-static/main.acdec141979b3122a4cd.bundle.js
  storybook-static/vendors~main.4db9d811e16878734c6b.bundle.js
  storybook-static/vendors~main.acdec141979b3122a4cd.bundle.js
Labels: enhancement, hooks

#12 Feature/button
  package-lock.json
  package.json
  src/components/Button/Button.stories.js
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/styles.test.js.snap
  src/components/Button/index.js
  src/components/Button/styles.js
  src/components/Button/styles.test.js
  src/routes/LandingRoutes.js
  src/setupTests.js
Labels: UI/UX, enhancement

#11 Feature/timer hook
  package-lock.json
  package.json
  src/components/TimerLabel/TimerLabel.stories.js
  src/components/TimerLabel/index.js
  src/components/TimerLabel/styles.js
  src/styles/GlobalStyles.js
  src/utility/dates/dates.test.js
  src/utility/dates/index.js
  src/utility/hooks/useTimer.js
  src/utility/hooks/useTimer.test.js
  yarn.lock
Labels: UI/UX, dependencies, enhancement

#14 Fix function name
  src/utility/api/api.test.js
  src/utility/api/index.js
  src/utility/enpoints/auth.js
  src/utility/enpoints/search.js
Labels: bug

#15 Testing/ TextInput TimerLabel
  src/components/TextInput/TextInput.test.js
  src/components/TextInput/__snapshots__/styles.test.js.snap
  src/components/TextInput/styles.test.js
  src/components/TimerLabel/TimerLabel.test.js
  src/components/TimerLabel/__snapshots__/styles.test.js.snap
  src/components/TimerLabel/index.js
  src/components/TimerLabel/styles.js
  src/components/TimerLabel/styles.test.js
Labels: testing

#17 Feature/login form
  package.json
  src/assets/event_up_logo.svg
  src/assets/landing_background.png
  src/auth-provider.js
  src/components/LandingWraper/Landingwraper.test.js
  src/components/LandingWraper/__snapshots__/stayles.test.js.snap
  src/components/LandingWraper/index.js
  src/components/LandingWraper/stayles.test.js
  src/components/LandingWraper/styles.js
  src/components/Logo/Logo.stories.js
  src/components/Logo/Logo.test.js
  src/components/Logo/__snapshots__/styles.test.js.snap
  src/components/Logo/index.js
  src/components/Logo/styles.js
  src/components/Logo/styles.test.js
  src/components/Spiner/Spiner.stories.js
  src/components/Spiner/Spiner.test.js
  src/components/Spiner/__snapshots__/styles.test.js.snap
  src/components/Spiner/index.js
  src/components/Spiner/styles.js
  src/components/Spiner/styles.test.js
  src/components/TextInput/index.js
  src/containers/Landing/index.js
  src/containers/SingIn/index.js
  src/context/auth-context.js
  src/routes/AppRoutes.test.js
  src/routes/LandingRoutes.js
  src/routes/LandingRoutes.test.js
  src/routes/PrivateRoute.js
  src/styles/GlobalStyles.js
  src/styles/animations.js
Labels: UI/UX, enhancement, hooks

#19 Feature/login form Validations
  src/components/TextInput/__snapshots__/styles.test.js.snap
  src/components/TextInput/index.js
  src/components/TextInput/styles.js
  src/components/TextInput/styles.test.js
  src/containers/SingIn/index.js
  src/utility/consts/const.test.js
  src/utility/consts/index.js
  src/utility/hooks/useFormFields.js
  src/utility/hooks/useFormFields.test.js
  src/utility/validations/index.js
  src/utility/validations/validations.test.js
Labels: documentation, enhancement, testing

#21 Feature/calendar timer input ui
  src/components/CalendarDatePicker/__snapshots__/styles.test.js.snap
  src/components/CalendarDatePicker/index.js
  src/components/CalendarDatePicker/styles.test.js
Labels: UI/UX

#34 Feature/register form
  package-lock.json
  package.json
  src/auth-provider.js
  src/containers/Landing/Landing.test.js
  src/containers/Register/Register.test.js
  src/containers/Register/index.js
  src/containers/SingIn/SingIn.test.js
  src/context/auth-context.js
  src/routes/LandingRoutes.js
  src/utility/consts/const.test.js
  src/utility/consts/index.js
  src/utility/validations/index.js
  src/utility/validations/validations.test.js
Labels: enhancement, hooks

#36 Add color Input
  package-lock.json
  package.json
  src/components/ColorInput/ColorInput.stories.js
  src/components/ColorInput/ColorInput.test.js
  src/components/ColorInput/__snapshots__/styles.test.js.snap
  src/components/ColorInput/index.js
  src/components/ColorInput/styles.js
  src/components/ColorInput/styles.test.js
Labels: UI/UX, testing

#18 Feature/button
  package-lock.json
  package.json
  src/components/Button/Button.stories.js
  src/components/Button/Button.test.js
  src/components/Button/__snapshots__/styles.test.js.snap
  src/components/Button/index.js
  src/components/Button/styles.js
Labels: UI/UX, enhancement

#37 hotfix/ Remove underline style to link elements by default
  src/styles/GlobalStyles.js
Labels: hotfix, styles

#39 Add Tag Component
  src/components/Tag/Tag.stories.js
  src/components/Tag/Tag.test.js
  src/components/Tag/__snapshots__/styles.test.js.snap
  src/components/Tag/index.js
  src/components/Tag/styles.js
  src/components/Tag/styles.test.js
Labels: UI/UX

#40 Fix .gitignore exclude node_modules folder
  .gitignore
Labels: hotfix

#38 Feature/navigation bar
  src/components/NavigationBar/NavigationBar.stories.js
  src/components/NavigationBar/NavigationBar.test.js
  src/components/NavigationBar/__snapshots__/styles.test.js.snap
  src/components/NavigationBar/index.js
  src/components/NavigationBar/styles.js
  src/components/NavigationBar/styles.test.js
  src/components/NavigationItem/NavigationItem.stories.js
  src/components/NavigationItem/NavigationItem.test.js
  src/components/NavigationItem/__snapshots__/styles.test.js.snap
  src/components/NavigationItem/index.js
  src/components/NavigationItem/styles.js
  src/components/NavigationItem/styles.test.js
Labels: UI/UX, enhancement

#41 Feature/add avatar component
  src/components/Avatar/Avatar.stories.js
  src/components/Avatar/Avatar.test.js
  src/components/Avatar/__snapshots__/Avatar.test.js.snap
  src/components/Avatar/index.js
  src/components/Avatar/styles.js
Labels: UI/UX

#42 Feature/api login
  src/auth-provider.js
  src/containers/Home/index.js
  src/containers/Register/index.js
  src/containers/SingIn/index.js
  src/context/auth-context.js
  src/utility/api/index.js
  src/utility/consts/const.test.js
  src/utility/consts/index.js
  src/utility/enpoints/auth.js
  src/utility/validations/index.js
  src/utility/validations/validations.test.js
Labels: API, enhancement, hooks

#45 Feature/add dashboard header
  src/components/DashboardHeader/DashboardHeader.stories.js
  src/components/DashboardHeader/DashboardHeader.test.js
  src/components/DashboardHeader/__snapshots__/DashboardHeader.test.js.snap
  src/components/DashboardHeader/index.js
  src/components/DashboardHeader/styles.js
Labels: UI/UX

#47 Feature/app wrapp
  src/components/AppWrapper/__snapshots__/styles.test.js.snap
  src/components/AppWrapper/index.js
  src/components/AppWrapper/styles.js
  src/components/AppWrapper/styles.test.js
  src/components/Button/index.js
  src/components/DashboardHeader/index.js
  src/components/DashboardHeader/styles.js
  src/components/NavigationBar/NavigationBar.test.js
  src/components/NavigationBar/index.js
  src/components/NavigationItem/index.js
  src/containers/Home/index.js
  src/routes/AppRoutes.js
Labels: UI/UX

#48 Feature/add text area input
  src/components/TextArea/TextArea.stories.js
  src/components/TextArea/TextArea.test.js
  src/components/TextArea/__snapshots__/styles.test.js.snap
  src/components/TextArea/index.js
  src/components/TextArea/styles.js
  src/components/TextArea/styles.test.js
Labels: UI/UX

#49 Added feature Event Row
  src/components/EventRow/EventRow.stories.js
  src/components/EventRow/EventRow.test.js
  src/components/EventRow/__snapshots__/EventRow.test.js.snap
  src/components/EventRow/index.js
  src/components/EventRow/styles.js
Labels: enhancement

#56 Feature/sponsors form
  src/components/FileInput/FileInput.stories.js
  src/components/FileInput/index.js
  src/components/NavigationBar/__snapshots__/styles.test.js.snap
  src/components/NavigationBar/styles.js
  src/components/SponsorItem/SponsorItem.stories.js
  src/components/SponsorItem/index.js
  src/components/SponsorItem/styles.js
  src/components/SponsorsForm/SponsorsForm.stories.js
  src/components/SponsorsForm/index.js
  src/components/Tag/index.js
  src/components/Tag/styles.js
  src/utility/api/index.js
  src/utility/enpoints/sponsors.js
  src/utility/enpoints/sponsors.test.js
  src/utility/hooks/useFormFields.js
Labels: API, UI/UX

#57 Feature template countdown
  src/assets/landing_background.jpg
  src/components/TemplateCountdown/TemplateCountdown.stories.js
  src/components/TemplateCountdown/index.js
  src/components/TemplateCountdown/styles.js
  src/components/TimerLabel/__snapshots__/styles.test.js.snap
  src/components/TimerLabel/styles.js
Labels: UI/UX, enhancement

#59 Feature/get user profile by auth
  src/auth-provider.js
  src/context/auth-context.js
  src/utility/api/index.js
  src/utility/enpoints/auth.js
  src/utility/enpoints/sponsors.js
Labels: API, documentation, enhancement, testing

#58 Feature/add template banner
  package.json
  src/components/templates/TemplateBanner/TemplateBanner.stories.js
  src/components/templates/TemplateBanner/index.js
  src/components/templates/TemplateBanner/styles.js
  src/components/templates/TemplateWrapper/TemplateWrapper.stories.js
  src/components/templates/TemplateWrapper/index.js
  src/components/templates/TemplateWrapper/styles.js
Labels: UI/UX, help wanted

#61 Fix Api Spoonsors with Auth
  src/components/SponsorItem/index.js
  src/components/SponsorsForm/index.js
  src/utility/api/index.js
Labels: API, enhancement

#63 Add Template Footer
  src/components/templates/TemplateFooter/TemplateFooter.stories.js
  src/components/templates/TemplateFooter/index.js
  src/components/templates/TemplateFooter/styles.js
  src/components/templates/TemplateWrapper/index.js
  src/components/templates/TemplateWrapper/styles.js
Labels: UI/UX
